// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zelwdlercsucfshaikcj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InplbHdkbGVyY3N1Y2ZzaGFpa2NqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkzNTQ4MjMsImV4cCI6MjA1NDkzMDgyM30.g6SsPFW31TsxGPQCsUepYlhsoL2IK4yN9_eO_T06sAg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
